### PR TITLE
fix: visual block mode

### LINKED ISSUE #387: Xcode13 broken: visual block mode
`<C-v>j` etc are broken.

unit test also failed: https://github.com/XVimProject/XVim2/runs/3782258463?check_suite_focus=true

### PR DESCRIPTION
**Pull request by r-plus**
close #387

### CODE REVIEW

File: XVim2/Xcode/SourceEditorViewWrapper.swift [hunk 1]
```diff
@@ -59,7 +59,14 @@ import Cocoa
...
 @_silgen_name("scev_wrapper_call4") func _set_selected_range(_: UnsafeRawPointer, _: XVimSourceEditorRange, modifiers: Int)
-@_silgen_name("scev_wrapper_call5") func _add_selected_range(_: UnsafeRawPointer, _: XVimSourceEditorRange, modifiers: Int)
+@_silgen_name("scev_wrapper_call5") func _add_selected_range(
+    _: UnsafeRawPointer,
+    _: XVimSourceEditorRange,
+    anchor: XVimSourceEditorRange?,
+    modifiers: Int,
+    scrollPlacement: Any?,
+    alwaysScroll: Bool
+)
```
Comment (r-plus) [inline XVim2/Xcode/SourceEditorViewWrapper.swift:69]: NOTE: `add_selected_range` method now have 6 arguments.
Our assembly implemented code (SourceEditorViewWrapper.s) support up to 8 arguments.
